### ISSUE TITLE
Goes missing after a revoot

### ISSUE THREAD

**Issue by TheBartoMan** [zachowj/node-red-contrib-home-assistant-websocket#1213]
### Describe the bug

Every time I reboot, this goes missing from the palette and I have to reinstall it in node-red

### Environment Information

Everything is fully up to date

**Comment by zachowj** [comment]
Does your setup meet all the requirements? Specifically Node-RED v3.1.1+?

**Comment by Galapagon** [comment]
I have the same problem, running 3.1.0 but I don't see a way to update.

**Comment by zachowj** [comment]
@Galapagon If you're running NR as an add-on you'll have to wait until it's updated.

**Comment by Galapagon** [comment]
Rats. Thank you Zachowj

**Comment by Xlinx64** [comment]
@Galapagon 
I found a temporary solution to update node-red since the addon would not allow me downgrade the package.
I added this to my addon configuration and it works. But make sure to delete this when the addon gets updated.
```
npm_packages:
  - node-red@3.1.1
```
You can also add this "node-red@3.1.1" to the ui editor in the npm packages section.

**Comment by Galapagon** [comment]
Great idea @Xlinx64 !
I was able to update NR to 3.1.1 then immediately remove it from the UI NPM and confirmed the updated version remains.
