### ISSUE TITLE
Wait Until node property check

### ISSUE THREAD

**Issue by bonanitech** [zachowj/node-red-contrib-home-assistant-websocket#131]
<img width="522" alt="Screenshot 2019-07-01 15 15 25" src="https://user-images.githubusercontent.com/29807944/60461082-81f2de80-9c13-11e9-93ea-207a07d2154f.png">

I think it's very weird to have to use a Home Assistant property in Wait Until. Since we are in Node-RED, in my humble opinion, the check should be done against the message object, as it is in most of the nodes. For example, in this case it would be `data.new_state.attributes.trigger`.

**Comment by zachowj** [comment]
Not sure I fully understand your issue here. What I understand you're describing is a switch node. Maybe if you have a use case I might be able to follow along better.

The wait-until node is part of the home assistant nodes where it listens for a property of a home assistant entity to change to a given value.  Not a property of the input message object for which there are already several nodes that can accomplish this task.

**Comment by bonanitech** [comment]
It's not really an issue, I just find it weird because we need to remember that detail when using this node. It's something out of the standard that most of us, Node-RED users, are used to. But don't worry about me, I'll try to get used to it. 😉

Just a small request, please improve the node help in that part to make it clear that it's a Home Assistant property that has to be used there. It took me some time to realize, I only noticed this when I looked more closely at a screenshot that you posted.

And thank you for your amazing work with these nodes.
