### ISSUE TITLE
Fields disappear (Call Service node)

### ISSUE THREAD

**Issue by ndoggac** [zachowj/node-red-contrib-home-assistant-websocket#1600]
### Describe the bug

When using Call Service node (now called action node) with domain switch the fields area, device and entity disappears when using services toggle or turn_off, or any action from the dropdown.

Even old flows are affected. Nodes known to have device entries in them are now missing.

Running 0.73.0 with latest home assistant everything.

### To Reproduce

create a new "call service" node. Entries for area, device, and entity exist.

Change Domain to "zwave_js", all three entries still exist.

Change Service to "multicast_set_value" and the entries for area & device disappear. Entity remains.

....

Edit old nodes that you know have things referenced by device name, realize the device entry area does not show up.

### Expected behavior

I expect the fields stated above not to disappear.

### Environment Information

Nothing shown in window.

### Additional context

Issues mistakenly posted in the add-on repository.

https://github.com/hassio-addons/addon-node-red/issues/1953
https://github.com/hassio-addons/addon-node-red/issues/1922

**Comment by zachowj** [comment]
Are you accessing the Node-RED UI via an iframe within Home Assistant? If so, try connecting directly to the Node-RED UI on port 1880 to check if the issue persists.

**Comment by ndoggac** [comment]
Tried with default theme, same behavior.
Tried in separate browser (Chrome) window with direct login, same behavior.
Tried in Firefox, Edge, Brave.  same behavior.

Area & Device fields disappear when you select certain options in the "Action" field dropdown.  Even editing past nodes where I know that devices were leveraged, they are missing.  Creating a new "action" node and the behavior is the same.

![nr](https://github.com/user-attachments/assets/8132333f-13bd-46c0-8006-9d0fd5ae3856)

**Comment by zachowj** [comment]
For the `zwave_js.multicast_set_value` action, the `area_id`, `device_id`, and `entity_id` should be placed under the `data` property, not within the `target` section. That's why the target section doesn't appear for this action.

You can refer to the documentation here:  
<https://www.home-assistant.io/integrations/zwave_js/#action-zwave_jsmulticast_set_value>

This change was introduced in version [0.66.0](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.66.0), as the properties were previously handled incorrectly. The update aligns the schema with Home Assistant’s behavior. If you build the same action in Home Assistant and switch to YAML mode, you'll see that these properties are correctly placed under the `data` property.

> In version 0.66.0, actions with entity IDs incorrectly placed in `target.entity_id` instead of `data.entity_id` will now throw errors.

**Comment by ndoggac** [comment]
zachowj thanks for the heads up.  I had missed the documentation/listing of the breaking changes.  <oof> that's a lot nodes affected for me.  consider this closed, thanks for fast responses.
