### ISSUE TITLE
Missing target (add entity, etc) in Action node for tts.google_translate_say

### ISSUE THREAD

**Issue by juansahome** [zachowj/node-red-contrib-home-assistant-websocket#1698]
### Describe the bug

When you place Action Node in Home Assistant and you select the action "tts.google_translate_say" the target fields are not loaded, so you cannot select the entities from the front-end view

### To Reproduce

1. Deploy Action Node
2. Select Action as tts.google_translate_say
3. No target menu is deployed so you cannot choose the target.

### Expected behavior

Being able to select the target, as for the rest of the nodes

### Screenshots

![image](https://github.com/user-attachments/assets/7186f97d-f4bf-4bbe-b5af-bec781543f83)

### Environment Information

Tried in two different devices (NAS & Raspberry) with HA OS.
HA Version: 2024.11.3
Node red version: 18.1.1

### Additional context

Similar issue: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1648#issuecomment-2473924571

**Comment by zachowj** [comment]
@juansahome For `tts.google_translate_say` actions, the `entity_id` must be specified in the `data` field, not the `target` field. This is why there's no target selector when using the action `tts.google_translate_say`. Additionally, `google_translate_say` is considered a [[legacy action](https://www.home-assistant.io/integrations/google_translate/#action-say-legacy)](https://www.home-assistant.io/integrations/google_translate/#action-say-legacy), and Home Assistant recommends using `tts.speak` instead.

@bertca Your issue seems different. It's likely that you're not running the latest version of the Home Assistant nodes.

**Comment by juansahome** [comment]
Hi @zachowj  thanks for your help!

I tested and it's working with the instructions you shared, Thank you a lot for your help! Needing to add each device inside data it's a little bit a mess when you have several, but at list is working.

THanks again!
