### ISSUE TITLE
Normalize node inputs/outputs like entity_id.

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#180]
The current solution is very inconsistent across all node types. For example history node has to be `msg.entityid` but current node has to be `msg.payload.entity_id`. The call service node allows you to set `msg.payload.entity_id` or use a `template` or get it from flow state. I think we should have the flexibility to use all three on every node.

I think consistency needs to happen for node outputs as well. Seems like some nodes completely change the payload type from object to string depending on if it returns state or history (compare   current state vs history nodes). Would be nice if we always returned a payload object like `msg.payload.state` or it just defaulted to `msg.state`. I think consistency goes a very long way to making the expected behavior normal.

**Comment by zachowj** [comment]
The get history and get templates nodes are the unloved nodes of the bunch. I have barely modified them since the original fork. So their inputs and outputs probably don't follow the current style. Nonbreaking pull requests are always welcome.

Most other node's inputs are pretty standard for all properties to be children of `msg.payload`. 

Outputs of nodes dealing with single entities output the state to `msg.payload`, for most use cases this the information wanted, and the [state object](https://www.home-assistant.io/docs/configuration/state_object/) is set to `msg.data`. This is true for the events: all, events: state, trigger: state, poll: state, and current state nodes. The event nodes `msg.data` will contain the state object for the previous and current state.

Nodes that deal with having multiple entities being returned have an array of state objects in `msg.payload`: get entities and get history.
 
Nodes that send information to HA output the payload that was sent (call service, fire event, sensor, and API). If an error occurs because of an invalid payload or another reason. There is an error message and no output sent.

I think that covers almost all the nodes that have an output by default.
