### ISSUE TITLE
Allow using environment variables in configuration

### ISSUE THREAD

**Issue by BeeHiveJava** [zachowj/node-red-contrib-home-assistant-websocket#244]
### Is your feature request related to a problem? Please describe.
It would be nice if we could use environment variables inside the configuration node. This would aid in deploying Node-RED in multiple environments. Right now when using an environment variable, Node-RED will give an error (and if you deploy it, it'll actually crash upon starting) - see screenshot.

### Describe the solution you'd like
Using environment variables either through the `$(NAME)` or `process.env.NAME`  notation, would be nice.

### Additional context
*Screenshot of Node-RED throwing an error when attempting to use an environment variable:*
![image](https://user-images.githubusercontent.com/5957362/83954130-aa815080-a846-11ea-9408-dbc297bc277e.png)

*Screenshot of the same behaviour working for MQTT:*
![image](https://user-images.githubusercontent.com/5957362/83954179-33988780-a847-11ea-9aa9-09f7abb2c8ed.png)

See also this discussion: https://discourse.nodered.org/t/mqtt-configuration-from-file-or-env-variable/11617

**Comment by zachowj** [comment]
It does work if you use environment variables the way the [documentation](https://nodered.org/docs/user-guide/environment-variables) shows, `${HOMEASSISTANT_URL}`. It still fails the UI side validation because it doesn't know what the env variable is at the time of saving the node data. The validation could be modified to check for the env pattern and allow it.

The crashing issue because of an invalid URL should be addressed though.

**Comment by BeeHiveJava** [comment]
I can confirm that is indeed working, thank you. I agree the UI validation is confusing, but that is certainly something I can work around.

Funnily enough I can't seem to reproduce the error anymore. Passing invalid configurations now correctly logs the error `[server:Home Assistant] Error: Invalid Base Url. Needs to start with http:// or https://`. I guess I'll close this and if I'm ever able to reproduce this error I'll let you know.
