### ISSUE TITLE
Add group. to zone node

### ISSUE THREAD

**Issue by cadavre** [zachowj/node-red-contrib-home-assistant-websocket#292]
### Is your feature request related to a problem? Please describe.

I can group a `person` entities – this gives me a possibility to track groups of people.

### Describe the solution you'd like

Currently we can select person. or device_tracker. in zone node. Please allow also groups.

### Describe alternatives you've considered

Zone node cannot treat multiple person. entities as group. Triggers are fired per person, so no possibility of making "everyone left" as described in #284.

### Additional context

Groups would allow to track >1 person as group.

**Comment by zachowj** [comment]
I believe this falls under the same category that #284 does. It is more of a state check than checking if an individual entity has moved from one zone to another.

The zone node uses the latitude and longitude of the previous state and current state of the updated entity to see if it has entered or left a zone. If you have a group with two `person` entities and one leaves a zone the other entity is not going to have a previous state so there is nothing check against. That's why I think this is better suited to be a state check rather than added to the zone node.

**Comment by cadavre** [comment]
I tend to think that zones in HA are useless, ech. :)

I did this (:p) to ask you:

![Untitled Diagram](https://user-images.githubusercontent.com/461796/100912063-504d0980-34d0-11eb-8d55-ee28febbdc87.png)

How can I design:

1. *A single node that* triggers an output when last person ("she") leaves `near` zone? Both are driving away from home.
2. *A single node that* triggers an output when first person ("he") enters `near` zone? Both are driving towards home.

---

As far as I see there's no way to do this. I hoped for this new `zone` node, but it doesn't do anything useful for me. :/

**Comment by zachowj** [comment]
What you have described can be done using the trigger-state node and the proximity intergration
