### ISSUE TITLE
States randomly stops updating after some time, with no errors

### ISSUE THREAD

**Issue by rasser900** [zachowj/node-red-contrib-home-assistant-websocket#381]
### Describe the bug

After some seemingly random time, the states just stop being synced from my HA instance, even though the HA object in NR shows as:
`isConnected: true`
`isRunning: true`
There are no errors in the container logs for NR and nothing around the time it stops working in HA logs.
If I restart the NR container, it works again. 
If I go change the name of my HA object, press the update button, and press deploy, it also starts working again.

### To Reproduce

Spin up NR container, connect to HA, make a flow.
Wait until the next day or so.

### Expected behavior

The states continue to update

### Screenshots

![image](https://user-images.githubusercontent.com/15357249/115990888-058a7600-a5c6-11eb-999f-d00c3278dcba.png)
![image](https://user-images.githubusercontent.com/15357249/115990966-63b75900-a5c6-11eb-9da0-242ca6109eaa.png)

### Example Flow

Not applicable

### Environment (please complete the following information):

- Node Red Version: 1.3.3
- Node.js Version: v10.24.1
- NR Home Assistant Plugin Version: 0.30.1
- Is Node Red running in Docker: yes

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:
-- Yes

### Additional context

This usually happens on my remote HA instance, running behind a traefik reverse proxy.
It has also happened once on my HA instance on my PI, where the NR container is also running.
Is there anywhere I can find additional debug information?

**Comment by Severin-S** [comment]
I have the same issue (also using docker & traefik) 
I noticed the issue always occurs around the same time I'm force reconnected by the ISP. Is it possible the addon can't handle a change of the IP address of the HA server?
I'll change my node-red config temporarily to use the the internal IP of my HA server instead of the domain name and report whether this is a working workaround.

**Comment by zachowj** [comment]
My guess would be that traefik is timing out the websocket.

**Comment by rasser900** [comment]
But if the connection times out, how come the "disconnected" event is not fired, and the connection reestablished? :thinking:

**Comment by rasser900** [comment]
I tried setting it up to connect through wireguard instead, no treafik involved, and the same behavior is present again now :/

**Comment by bjekel** [comment]
I have the same issue as well. HA is running on a Raspberry Pi and node-red is running on a different machine using docker. Node-red is connecting to HA using the local IP address, so in my case Traefik shouldn't really be a problem.
The issue is really annoying because it happens about every hour, but I also haven't found the cause of the issue or a workaround yet.

**Comment by bjekel** [comment]
I've found the source of my issue. I had some docker containers which used macvlan and it caused problems in my network. So the nodered container sometimes lost its connection to the network and it seems that the websocket didn't reconnect when the connection was restored.

**Comment by sstratoti** [comment]
I'm having the same issue. I'm on 33.0 though, just updated to 33.1 a moment ago.

I'm running node-red in docker, and home assistant in docker - both are on the same machine, however I'm connecting to HA through DNS and HTTPS, not locally.

**Comment by sstratoti** [comment]
I've set up the logger in my configuration.yaml, and restarted HASS. Once it restarted, node-red actions that I was waiting for fired right away. So I think its reconnecting fine. I think your suspicion that its on the HA end might be correct. I'll report back with any logs the next time it happens.

**Comment by sstratoti** [comment]
I've still been getting these, but I've had to restart it and couldn't take the time to copy out the log file and sort through it until today.

In the log file for HA I see errors related to this issue: https://github.com/thomasloven/hass-browser_mod/issues/159

Out of curiosity, @Severin-S and @rasser900 - are you using browser_mod at all?

**Comment by rasser900** [comment]
I am not using browser_mod.
I "fixed" it by using remote home assistant to sync the states of the entities I need from the remote instance to my local instance running on the PI itself and unlinking nodered from my remote instance.

**Comment by Severin-S** [comment]
@sstratoti I'm also not using browser_mod

Yesterday I've setup a clean new HA instance and a new NodeRed and collected the logs @zachowj mentioned.

My fritzbox logs say that a got a new IP address at 4:23:38 AM. I did *not* verify that that's also the time NodeRed lost the connection to HA but the logs seem to support the theory that the issue is related to the changing IP.
```
2021-06-23 04:23:42 DEBUG (Recorder) [homeassistant.components.recorder] Sending keepalive
2021-06-23 04:24:12 DEBUG (Recorder) [homeassistant.components.recorder] Sending keepalive
2021-06-23 04:24:12 DEBUG (MainThread) [async_upnp_client.search] Sending M-SEARCH packet
2021-06-23 04:24:12 DEBUG (MainThread) [async_upnp_client.traffic.ssdp] Sending M-SEARCH packet: b'M-SEARCH * HTTP/1.1\r\nHOST:239.255.255.250:1900\r\nMAN:"ssdp:discover"\r\nMX:4\r\nST:ssdp:all\r\n\r\n'
2021-06-23 04:24:34 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140187048509392] Connection closed by client
2021-06-23 04:24:34 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140187048509392] Disconnected
2021-06-23 04:24:42 DEBUG (Recorder) [homeassistant.components.recorder] Sending keepalive
2021-06-23 04:25:12 DEBUG (Recorder) [homeassistant.components.recorder] Sending keepalive
2021-06-23 04:25:12 DEBUG (MainThread) [async_upnp_client.search] Sending M-SEARCH packet
2021-06-23 04:25:12 DEBUG (MainThread) [async_upnp_client.traffic.ssdp] Sending M-SEARCH packet: b'M-SEARCH * HTTP/1.1\r\nHOST:239.255.255.250:1900\r\nMAN:"ssdp:discover"\r\nMX:4\r\nST:ssdp:all\r\n\r\n'
```

**Comment by sstratoti** [comment]
Had to turn off debug for websocket because my log file grew way too large waiting for the issue to happen again. And it happened again this morning.
I removed and resolved errors that were present in my log, thinking it may have been something else causing the connection issue (i.e., like browser_mod). 
This morning when I realized that my node red events weren't firing, I restarted the node-red docker container. Everything came back up and is working just fine.
I added "warning" level to the websocket logger entry. Is there a way to debug the connection issue inside of NodeRed? Or does it doesn't realize that there is a connection problem?

I think I can query sensor.time in HA, and if its out of date...send myself an email? I can't send an iOS message through HA because that'd require a connection to HA...

**Comment by Smilebags** [comment]
I'm also facing this running HA and NR in two docker containers on the same machine. Has anyone found a reliable solution to this? I was hoping digging into the code it would be easy to find the missing websocket 'disconnect' handler, to simply add a reconnection step, but that doesn't seem to be so trivial.

**Comment by sstratoti** [comment]
My issue was connecting to HA through my domain with an Nginx front end. Somewhere in my settings, the web socket connection would time out. Since running it directly against the docker instance instead of by domain (I.e. referencing the docker container name rather than the domain I’d set up) it’s been running perfectly. So I’d recommend what Zach was suggesting - use local IP or even the container name. It resolved my issues.

**Comment by Smilebags** [comment]
I have an identical setup, and was also doing the same. I'm using `--net host` so I'm just referencing it with `localhost:port`, will see how that goes. Regardless, I feel like a reconnection process would be ideal. Without it, the system is unnecessarily flaky.

**Comment by walthowd** [comment]
I can just add it's not a docker networking issue, or name resolution. I'm experiencing the same bug, both `homeassistant` and `node-red` containers are running in `network_mode: host`. Node-RED server node connection to HA is using `https://127.0.0.1:8123`

This setup works reliably with `node-red-contrib-home-assistant-websocket` up to version `0.30.1` but breaks on later versions. I haven't had a chance to chase it yet. 

I'm assuming it's only an issue with large node-red and possibly a WS connection issue/limit -- I have ~ 1,100 HA nodes and have had to previously patch HA to allow higher connection limits:

```
  homeassistant.components.websocket_api.http:
    MAX_PENDING_MSG: 4096
    PENDING_MSG_PEAK: 2048
```
