### ISSUE TITLE
Mustache template in call service node needs to be rendered before stringified?

### ISSUE THREAD

**Issue by frazzyfin** [zachowj/node-red-contrib-home-assistant-websocket#47]
I'm having trouble using the mustache templates in the call service node, data field.

I'm populating the `callback query_id` field with a number located in` msg.payload.event.id` but this isn't valid json as it sees the mustache template as a being a string and not a number, which it should be.

```
{
    "message": "Lights have been turned off",
    "callback_query_id": {{msg.payload.event.id}}
}
```
Could this be because the mustache template is not being rendered until _after_ it is parsed as a json string?

**Comment by zachowj** [comment]
The issue you're running into that it tries to validate the `data` property when you update the call-service node and since it's not a valid JSON string you see the validation error. You really can't render the template on the front end because you don't have the proper data to fill it in. There are probably some changes I can make to make this work more eloquently.

In the meanwhile, you could use quotes around `{{payload.event.id}}` to make it a valid JSON string. The one downside is that it converts the `id` to a string. If that works for you though it might be a temporary solution.

```
{
    "message": "Lights have been turned off",
    "callback_query_id": "{{payload.event.id}}"
}
```

Side note: I need to document it better but the template is built off the `msg` object so `msg.payload.event.id` as a template is `{{payload.event.id}}`

**Comment by zachowj** [comment]
No, you can run `mustache.render()` on apiData at that point because it's an Object and render requires a string.

https://github.com/janl/mustache.js/blob/38b1448e65f1d4716c3e3ad792ae6ab3aaf487ab/mustache.js#L648-L653
