### ISSUE TITLE
Current State node only allows "for" duration when "is" is selected, but not ">", "<", etc.

### ISSUE THREAD

**Issue by jschwalbe** [zachowj/node-red-contrib-home-assistant-websocket#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/8005921/150688733-e6ef358e-faed-41c9-8c1c-db71773becc9.png)

The `current_state` node now has a `for:` duration (thank you for adding this! https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/289). However, changing from "is" to ">" or "<", or anything other than "is not", "in" or "not in" causes the `for:` duration option to disappear.

This seems to be an oversight rather than a decision to leave it out, since the `state_changed` node does *not* behave this way.

Any thoughts?

### This package's version

0.41.3

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.1.4

### Node.js version

?

**Comment by zachowj** [comment]
It was a conscious decision. The way the current state node `for` check works is by checking if the `if state` is `true` looking at the last updated timestamp from HA and comparing that to the value in the `for` check. This works for `is` and `is not` because it's checking a static string/number value. With greater than or less than this value can have a range of valid values and with each change, the `last_updated` timestamp gets also updated. So there is no tracking of when a value went over or under a threshold.

With the events: state node there is an internal timer watching if the `if state` is true and keeping tracking of that. As it is already checking each time the entity is watching changes. With the current state node, the state is only getting checked on an input to the node.

**Comment by jschwalbe** [comment]
Ah, ok. I’m that case, perhaps I’m asking the wrong question. 

Rather than asking if it’s been a certain state for x minutes, I’m really needing to ask “has it been this way for x minutes *since this node started*?”

Does that reframe things? Then instead of needing to monitor its state at all times, the monitoring would just start when the node instructs it to.

**Comment by jschwalbe** [comment]
Another way of saying it might be
“is the state > 5 over the next 3 minutes?”

Would that be worthwhile to have, or just confusing? Thanks again for the amazing tool you’ve created!

**Comment by zachowj** [comment]
That sounds you just want a current-state node into a wait-until node.

**Comment by zachowj** [comment]
I just answered a question like this on discord. 

![image](https://user-images.githubusercontent.com/37859597/150692388-c217f278-af08-4313-91ba-3d54cc14b40a.png)

https://pastebin.com/8E9zsYeX
