### ISSUE TITLE
Upgrade to v0.43.1 fails

### ISSUE THREAD

**Issue by OliverGreenforest** [zachowj/node-red-contrib-home-assistant-websocket#613]
### Describe the bug

On a Raspberrymatic, latest version, update to v0.43.1 fails. The node disappears from the installed nodes resulting in unknown node types error message of Nodered stopping all flows.

### To Reproduce

Palette, upgrade node-red-contrib-home-assistant-websocket

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

No

### Node-RED version

7.2.1 (Redmatic)

### Node.js version

12.22

**Comment by zachowj** [comment]
What do your node-red logs show?

**Comment by OliverGreenforest** [comment]
Unfortunately, I deleted the logs having restored Raspberrymatic entirely from a backup. As far as I remember Node-Red issued a message "Cannot read property 'nodes" of null." BTW: After my first restore I tried again to update to v0.43.1. Same result, node completely disappeared and an installation was impossible. Current version v0.41.3 works fine.

**Comment by klingon888** [comment]
Same failure. Reverting back to 0.41.3 works fine. I unfortunately also dont have my logs.

**Comment by gborri** [comment]
i've installed node-red in docker.

The error log is:

![image](https://user-images.githubusercontent.com/3479510/158379403-e03b6b25-aa23-4247-9266-26711b788663.png)

**Comment by zachowj** [comment]
@gborri What docker container are you running? What version of node is the docker container running?

**Comment by gborri** [comment]
nodered/node-red:latest

**Comment by Rigear** [comment]
I am also running node-red within a container and this is what I did to get things working.

Based on this issue talking about the WS library, I did an `npm install bufferutil` and `npm install utf-8-validate` with my node-red's data mount location. This worked for me because I also have nodejs installed on the container host itself. 

Once the packages were installed, node-red came up without any issues after I restarted the container with `node-red-contrib-home-assistant-websocket` installed at `0.43.1`

**Comment by zachowj** [comment]
@Rigear what version of node is running in the container?

**Comment by Rigear** [comment]
Originally 12. I then tried 14 and 16. Using the `nodered/node-red` container. 

I'm now soaking with the `2.2.2-16` tagged image.

When I upgraded to the `0.43.1` release of this module tonight, I also removed the `serialport` and `email` node-red modules since I wasn't using them. (Bad process on my part, should have only done one thing at a time in-between container restarts)

**Comment by gborri** [comment]
same problem also on nodered v3.0.0
