### ISSUE TITLE
High CPU usage due to reconnection issues

### ISSUE THREAD

**Issue by PeeVv** [zachowj/node-red-contrib-home-assistant-websocket#76]
I'm using the Node Red add-on (v1.2.3 containing library version v0.5.1) on Hassio (v0.85.1). When restarting Home Assistant, Node Red continuously tries to reconnect hundreds of times causing a high CPU load.

<img width="1329" alt="schermafbeelding 2019-01-13 om 18 19 01" src="https://user-images.githubusercontent.com/5428633/51088465-4ac16b80-1760-11e9-8fe1-7d1d1733dca7.png">
<img width="304" alt="schermafbeelding 2019-01-13 om 18 19 52" src="https://user-images.githubusercontent.com/5428633/51088468-4c8b2f00-1760-11e9-9777-afeef2cfd1d4.png">

**Comment by zachowj** [comment]
This is a weird issue in that it's actually working correctly but due to how hass.io proxy works this happens.

Normal Operation:

1. Websocket connection to HA disconnects
2. node-red tries to reconnect instantly and port is unresponsive 
3. 5 second delay and try and attempt reconnect
4. rinse and repeat step 3 until connection is made

Hass.io Operation:

1. Websocket connection to HA disconnects
2. node-red tries to reconnect instantly
3. hass.io websocket proxy "fakes" a successful connection (this makes node-red think that is has successful connected)
4. then the proxy checks if HA is online and if it's not it disconnects the websocket
5. node-red tries to reconnect instantly without a delay because it thougt it was a successful connected
6. repeat 3-4

I feel that is more of a hass.io proxy issue where it should check if HA is online before it "fakes" it connection. I might be able to fiddle with the reconnection logic for hass.io users but I'll have to think about the best appoarch.
