### ISSUE TITLE
Areas

### ISSUE THREAD

**Issue by bjohnson8949** [zachowj/node-red-contrib-home-assistant-websocket#91]
Having areas in node-red would be amazing. I checked in node-home-assistant.js and I don't see getAreas so unless I am looking in the wrong places I don't believe its currently supported. Right now I do a lot of this through names matching patterns and determining room\area but this would allow me to control devices easily based on what room they are in. 

Thanks in Advance!

**Comment by zachowj** [comment]
This just a very rough first draft. Looking for input on things that should be changed or pitfalls missed.

- Areas are assigned to devices
- Devices come from integrations
- Devices can have many entities

Areas are only going to work on components that have had integration support added.

Currently, there are no events for when an Area is created, updated or deleted. To be able to get this information into node-red and to keep it updated it will have to be polled at an interval. 5 minutes?

My plan currently is to remove devices from the equation and only work with entities and areas. Areas don’t have very nice ids so we’ll be using a [slugify](https://ww.npmjs.com/package/slugify) version of the area name. They will also only work when using the substring or regex filter type. The slugified area name will be prepended to the entity_id.

Example:
TP-Link switch with an entity id of `switch.kitchen_light` would become `kitchen.switch.kitchen_light`
TP-Link light with an entity_id of `light.kitchen_counter` would become `kitchen.light.kitchen_counter`

If both these entities were assigned to the area kitchen you would be able to listen for events like.

Regex: `^kitchen\.`
Substring: `kitchen.`

If you had multiple lights assigned to the area kitchen you could do something like below.

Substring: `kitchen.light.` listen for all lights assigned to the kitchen area

This does create a small **breaking change**. If one had used a regex filter with `^`, e.g. `^light\.`, this would no longer work because the value that it would be checking against would be `kitchen.light.kitchen`. This would not affect entity ids that don’t have areas assigned to them as they would continue to operate exactly the same as they did before.

The entity_id of a state object would not be changed but a new `area` object would be added to the state object that would include `area_id`, `name` and `slug`.

```
{
    "entity_id": "light.kitchen",
    "state": "on",
    "attributes": {
         ...
    },
    "last_changed": "2019-03-23T17:42:16.908892+00:00",
    "last_updated": "2019-03-24T00:54:30.003995+00:00",
    "context": {
        "id": "6cfc406cb81a6cfc406cb81a",
        "user_id": null
    },
    "timeSinceChangedMs": 25977213,
    "area": {
          "area_id": "6cfc406cb81a",
          "name": "Kitchen",
          "slug": "kitchen"
     }
}
```

**Comment by zachowj** [comment]
Going to archive this until HA does a little more with areas to see where they end up.

Here's a solution that can be accomplished with what's available now.

<https://community.home-assistant.io/t/example-get-state-changed-events-based-on-area/160366?u=kermit>
