### ISSUE TITLE
Home assistant time node not firing randomly

### ISSUE THREAD

**Issue by blair287** [zachowj/node-red-contrib-home-assistant-websocket#914]
### Describe the bug

Hi have an issue with the time node, this has been working flawlessly for months but 2 weeks ago its randomly started not actually doing anything the node changes from in x to in the past but no output is fired flso my flows aren't starting.

Nothing in my flow has been changed no settings etc and if I change offset to test it it seems to work.

But randomly stuff won't have started I check in node red and it says in past but nothing else after shows history like there was no output from the time node.

Cheers.

### To Reproduce

Kinda hard to reproduce and not happening all the time.

### Expected behavior

Node should fire reliably

### Screenshots

![image-2](https://user-images.githubusercontent.com/44187409/233454474-9bade8bf-e091-41be-87d7-80e22e1b63b9.png)

### This package's version (not the Home Assistant add-on version)

0.49.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

14.1.4

### Node.js version

14.1.4

### Additional context

Screenshot tou can see the node now shows in the past but no other nodes show any info like theu never received any data.

**Comment by ScottG489** [comment]
Ok I think I might be having the same issue as you and it sounds like it may have started around the same time as you as well. It's been seriously bugging me because it's such a strange issue.

To make sure we're having the same issue, let me explain mine in more detail.

So I have a recurring calendar event. My time node configuration uses that calendar entity and then for the property it uses `attributes.start_time`. It also has an offset of -30 minutes. I have a few output properties, but otherwise nothing else is checked. I actually have about 5 of these nodes at decreasing offsets (basically reminders leading up to the event).

The behavior I've witnessed is that the first node with the -30 offset always fires, but it fires late. I also can't verify this completely, but the time at which it fires also seems to slide. So at first it fired at maybe -29m33s, then 28m42, etc. As time goes on it seems to fire a little more late. The later nodes I think never end up firing (especially never the one with no offset). I think this is because they become too late and the node gets marked as in the past. I'm not sure exactly what this cutoff time is, though.

It doesn't seem like it's a problem with the time of the container NR is running in. I connected to it and the time seems fine.

If this was due to an update, it looks like there was an add-on update ([v14.1.4](https://github.com/hassio-addons/addon-node-red/releases/tag/v14.1.4) was released on April 11th) which bumped this websocket package's version from 0.49.0 to 0.49.1.

**Can you confirm if this was a problem for you before or after that release if you're using the add-on?**

Looking at the [changes in that release](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/compare/v0.49.0...v0.49.1), curiously it looks like the `node-cron` package was updated to [v2.3.0](https://github.com/kelektiv/node-cron/compare/v2.2.0...v2.3.0). Trying to sift through those changes though I'm afraid is where things get too fuzzy for me, and I don't see any issues or PRs that might be related to this problem in that repo.

Otherwise, could you provide a little more information about the configuration of your time nodes and any other behavior you might have observed?

**Comment by blair287** [comment]
> Ok I think I might be having the same issue as you and it sounds like it may have started around the same time as you as well. It's been seriously bugging me because it's such a strange issue.
> 
> To make sure we're having the same issue, let me explain mine in more detail.
> 
> So I have a recurring calendar event. My time node configuration uses that calendar entity and then for the property it uses `attributes.start_time`. It also has an offset of -30 minutes. I have a few output properties, but otherwise nothing else is checked. I actually have about 5 of these nodes at decreasing offsets (-15, -5, etc., basically reminders leading up to the event).
> 
> The behavior I've witnessed is that the first node with the -30 offset always fires, but it fires late. I also can't verify this completely, but the time at which it fires also seems to slide. So at first it fired at maybe -29m33s, then 28m42 the next day, etc. As time goes on it seems to fire a little more late. The later nodes I think never end up firing (especially never the one with no offset). I think this is because they become too late and the node gets marked as in the past. I'm not sure exactly what this cutoff time is, though.
> 
> It doesn't seem like it's a problem with the time of the container NR is running in. I connected to it and the time seems fine.
> 
> If this was due to an update, it looks like there was an add-on update ([v14.1.4](https://github.com/hassio-addons/addon-node-red/releases/tag/v14.1.4) was released on April 11th) which bumped this websocket package's version from 0.49.0 to 0.49.1.
> 
> **Can you confirm if this was a problem for you before or after that release if you're using the add-on?**
> 
> Looking at the [changes in that release](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/compare/v0.49.0...v0.49.1), curiously it looks like the `node-cron` package was updated to [v2.3.0](https://github.com/kelektiv/node-cron/compare/v2.2.0...v2.3.0). Trying to sift through those changes though I'm afraid is where things get too fuzzy for me, and I don't see any issues or PRs that might be related to this problem in that repo.
> 
> Otherwise, could you provide a little more information about the configuration of your time nodes and any other behavior you might have observed?

I'm not sure on the version I was running when it was OK but my time node is set up the same way calendar with attribute start time. My other time nodes not using calendar or offset have worked flawlessly. Saying that the issue hasn't happened for last couple weeks.

**Comment by ScottG489** [comment]
Strange. I wonder if there's something weird with the calendar start time attribute changing? I find that highly unlikely, but maybe I'll put that attribute into a sensor and see if it's ever changing.

I think it's more likely that it has something to do with the offset or just the node in general. However, my one node that does use the calendar and no offset also doesn't work properly, so that wouldn't add up.

**Comment by ScottG489** [comment]
So I restored a backup I had of v14.1.3 and I'm still getting this problem. So it doesn't seem related to node-cron or other changes in the next version.

I'm going to try a few backups with older versions as well.

**Comment by ScottG489** [comment]
So I've gone back a few versions and becoming fairly confident that it isn't related to the version. I'm now currently testing my oldest version (13.5.3) and if this doesn't work I'll pursue other options.

Does anyone know how else I could troubleshoot this issue?

**Comment by ScottG489** [comment]
Still an issue.

**Comment by ScottG489** [comment]
So it turns out that I was on a very old (~0.42?) version of package. I was under the impression that this updated along with the add-on since the add-on mentions in it's release notes new versions of this node. However, I was looking in my palettes and noticed an update button and the current version being very old.

Anyways, now that I've updated I'll see if this issue is still present for me.

**Comment by ScottG489** [comment]
So it's been about a week and I haven't seen any drift with the nodes running late or with them not kicking off at all.

@blair287 Can you confirm you are still having this issue on the latest version of this websocket lib? It looks like my issue was just that I needed to manually update it inside of NR.

I'd be interested to see if there's a way to have this auto update or at least update when I update the NR addon in HA.
